server:
  port: 8081
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false  # Set to true in production with HTTPS

logging:
  level:
    org.springframework.security: DEBUG



spring:
  session:
    store-type: none  # or redis/jdbc if using distributed sessions
  security:
    oauth2:
      client:
        registration:
          client1:
            client-id: client1
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/client1
            scope: openid,read
        provider:
          client1:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            jwk-set-uri: http://localhost:9000/oauth2/jwks